// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

// Prisma 마이그레이션/푸시는 직접 연결이 필요합니다 (pgbouncer는 트랜잭션 모드에서 문제 발생)
// DIRECT_DATABASE_URL이 있으면 사용, 없으면 DATABASE_URL에서 포트를 5432로 변경
function getDirectDatabaseUrl() {
  if (process.env.DIRECT_DATABASE_URL) {
    return process.env.DIRECT_DATABASE_URL;
  }

  const url = process.env.DATABASE_URL || '';
  if (!url) return '';

  // pgbouncer 포트(6543)를 직접 연결 포트(5432)로 변경
  const directUrl = url
    .replace(':6543/', ':5432/')
    .replace('?pgbouncer=true', '')
    .replace('&pgbouncer=true', '');

  return directUrl;
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: getDirectDatabaseUrl(),
  },
});
