/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    footer: Footer;
    'chairman-message': ChairmanMessage;
    'academic-calendar': AcademicCalendar;
    catalog: Catalog;
    scholarship: Scholarship;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'chairman-message': ChairmanMessageSelect<false> | ChairmanMessageSelect<true>;
    'academic-calendar': AcademicCalendarSelect<false> | AcademicCalendarSelect<true>;
    catalog: CatalogSelect<false> | CatalogSelect<true>;
    scholarship: ScholarshipSelect<false> | ScholarshipSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  slides?:
    | {
        /**
         * PC/태블릿에서 표시될 이미지 (16:9 권장)
         */
        image: number | Media;
        /**
         * 모바일에 최적화된 이미지가 있다면 등록하세요. 비워두면 데스크탑 이미지가 자동으로 안전하게 표시됩니다.
         */
        mobileImage?: (number | null) | Media;
        /**
         * 이미지 표시 방식을 선택하세요.
         */
        layoutSettings?: {
          /**
           * ✅ 체크: 이미지 전체를 보여주고 여백은 블러 처리 (텍스트/로고가 있는 포스터 권장)
           * ❌ 미체크: 화면을 꽉 채우고 이미지 일부가 잘릴 수 있음 (배경 사진 권장)
           */
          isPoster?: boolean | null;
        };
        title?: string | null;
        subtitle?: string | null;
        description?: string | null;
        buttons?:
          | {
              label: string;
              link: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer 영역에 표시될 연락처 정보를 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Footer에 표시될 연락처 정보를 입력하세요.
   */
  contact: {
    /**
     * Footer에 표시될 대학교 이름
     */
    universityName: string;
    /**
     * 예: 123-456-7890
     */
    phoneEn: string;
    /**
     * 예: 123-456-7890
     */
    phoneKo: string;
    /**
     * 대학 대표 이메일 주소
     */
    email: string;
    /**
     * 대학교 주소
     */
    address: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * /about - Chairman's Message 섹션에 표시될 내용을 관리합니다
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chairman-message".
 */
export interface ChairmanMessage {
  id: number;
  /**
   * 섹션의 메인 제목입니다
   */
  title: string;
  /**
   * 제목 아래에 표시될 소제목입니다
   */
  subtitle?: string | null;
  /**
   * 본문 내용을 입력하세요
   */
  description?: string | null;
  /**
   * 섹션에 표시될 이미지를 업로드하세요
   */
  image?: (number | null) | Media;
  /**
   * 작성자 이름을 입력하세요 (예: Kwangsung Park, Ph.D.)
   */
  author?: string | null;
  /**
   * 작성자의 직책을 입력하세요 (예: Chairman of the Board)
   */
  authorTitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 학사 일정(Academic Calendar)과 주요 행사를 학기별로 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-calendar".
 */
export interface AcademicCalendar {
  id: number;
  /**
   * 행정 직원이 학기 단위로 일정을 추가할 수 있습니다.
   */
  terms?:
    | {
        /**
         * 예: 2026 Spring, Fall 2025
         */
        name: string;
        events?:
          | {
              /**
               * 예: Registration, Classes Begin
               */
              title: string;
              /**
               * 일정 시작일
               */
              startDate: string;
              /**
               * 당일 행사인 경우 비워두세요.
               */
              endDate?: string | null;
              /**
               * 선택 사항. 예: 9:00 AM, 2:00–4:00 PM. 있으면 날짜 옆에 표시됩니다.
               */
              time?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 입학 요강 PDF 파일과 타이틀, 해당 연도를 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog".
 */
export interface Catalog {
  id: number;
  /**
   * 예: 학사과정 입학 요강
   */
  title: string;
  /**
   * 몇 년도 자료인지 표시 (예: 2026 - 2027)
   */
  subtitle: string;
  /**
   * 오직 PDF 파일만 업로드 가능합니다.
   */
  file: number | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Scholarship 페이지에 표시될 내용을 관리합니다.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scholarship".
 */
export interface Scholarship {
  id: number;
  /**
   * 페이지 최상단에 표시되는 제목입니다.
   */
  pageTitle: string;
  /**
   * 페이지 제목 아래에 표시되는 짧은 설명 문구입니다.
   */
  pageDescription?: string | null;
  /**
   * 장학금 정책의 일반 원칙 본문입니다. 개행(
   * )을 사용하여 단락을 구분합니다.
   */
  generalPrinciples: string;
  /**
   * 장학금 유형별 카테고리를 관리합니다. 순서를 드래그하여 변경할 수 있습니다.
   */
  categories?:
    | {
        /**
         * 예: Family & Relationship Scholarships
         */
        title: string;
        /**
         * 이 카테고리에 속하는 장학금 항목들입니다.
         */
        scholarships?:
          | {
              /**
               * 예: Student Couple Scholarship
               */
              title: string;
              /**
               * 장학금 지원 목적 (선택 사항)
               */
              purpose?: string | null;
              /**
               * 수혜 대상 조건 (선택 사항)
               */
              eligibility?: string | null;
              /**
               * 지급 방식 또는 규정 (선택 사항)
               */
              policy?: string | null;
              /**
               * 실제 지급되는 혜택 내용 (필수)
               */
              benefit: string;
              /**
               * 추가 요건 (선택 사항, 예: GPA 기준)
               */
              requirement?: string | null;
              /**
               * 갱신 조건 등 기타 조건 (선택 사항)
               */
              condition?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 자격 요건, 행정 절차, 면책 조항 등 일반 정책 섹션을 관리합니다.
   */
  generalSections?:
    | {
        /**
         * 예: General Qualifications & Compliance
         */
        title: string;
        /**
         * 섹션 본문입니다. 개행(
         * )으로 단락을 구분합니다.
         */
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        image?: T;
        mobileImage?: T;
        layoutSettings?:
          | T
          | {
              isPoster?: T;
            };
        title?: T;
        subtitle?: T;
        description?: T;
        buttons?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        universityName?: T;
        phoneEn?: T;
        phoneKo?: T;
        email?: T;
        address?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chairman-message_select".
 */
export interface ChairmanMessageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  image?: T;
  author?: T;
  authorTitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academic-calendar_select".
 */
export interface AcademicCalendarSelect<T extends boolean = true> {
  terms?:
    | T
    | {
        name?: T;
        events?:
          | T
          | {
              title?: T;
              startDate?: T;
              endDate?: T;
              time?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog_select".
 */
export interface CatalogSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scholarship_select".
 */
export interface ScholarshipSelect<T extends boolean = true> {
  pageTitle?: T;
  pageDescription?: T;
  generalPrinciples?: T;
  categories?:
    | T
    | {
        title?: T;
        scholarships?:
          | T
          | {
              title?: T;
              purpose?: T;
              eligibility?: T;
              policy?: T;
              benefit?: T;
              requirement?: T;
              condition?: T;
              id?: T;
            };
        id?: T;
      };
  generalSections?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}